# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben Rakestraw
email: benrakestraw1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a site for me to try to learn website building and administration. 
  I will also post blogs... I guess. 
  I am trying to do everything from the terminal in linux.
  Someday I will get around to reserving a real domain.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: benrakestraw
github_username:  btr886m

# Build settings
markdown: kramdown
